FROM node
RUN yarn config set registry https://registry.npm.taobao.org 
RUN yarn global add parse-dashboard

ENV PARSE_DASHBOARD_SERVER_URL "http://localhost:1337/parse"
ENV PARSE_DASHBOARD_MASTER_KEY "myMasterKey"
ENV PARSE_DASHBOARD_APP_ID "myAppId"
ENV PARSE_DASHBOARD_APP_NAME "MyApp"
ENV PORT "4040"
CMD parse-dashboard --allowInsecureHTTP true


