---
apiVersion: v1
kind: Namespace
metadata:
  name: devops-parse


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-parse
  namespace: devops-parse
data:
  APP_NAME: AppDevopsParse
  APP_ID: 2NjRq2vT9iTScCj5Oa95ha1CygCnrcityNbaBYMm
  MASTER_KEY: 0cuGH3wqLJipUgHMxGjpSjV96uEL8g54zl5kJmlA
  DASHBOARD_USER_ID: user
  DASHBOARD_USER_PWD: pass

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mongo-db
  namespace: devops-parse
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo
        image: 192.168.250.75:5000/mongo
        ports:
        - name: mongo
          containerPort: 27017
        args: ["--storageEngine", "wiredTiger"]
        volumeMounts:
        - name: vol-data-mongo
          mountPath: /data/db
        readinessProbe:
          tcpSocket:
            port: 27017
          initialDelaySeconds: 15
          timeoutSeconds: 1          
      volumes:
      - name: vol-data-mongo
        emptyDir: {}
        # hostPath:
          # directory location on host
          # path: /data/k8s/mysql/vol/base
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongo-db
  labels:
    app: svc-mongo-db
  namespace: devops-parse
spec:
  ports:
  - port: 27017
  selector:
    app: mongo-db

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: parse-server
  namespace: devops-parse
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: parse-server
    spec:
      containers:
      - name: parse-server
        image: 192.168.250.75:5000/devops/pserver
        ports:
        - name: svr-port
          containerPort: 1337
        env:
        - name: PARSE_SERVER_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: config-parse
              key: APP_NAME
        - name: PARSE_SERVER_APP_ID
          valueFrom:
            configMapKeyRef:
              name: config-parse
              key: APP_ID
        - name: PARSE_SERVER_MASTER_KEY
          valueFrom:
            configMapKeyRef:
              name: config-parse
              key: MASTER_KEY
        - name: PARSE_SERVER_DATABASE_URI
          value: mongodb://svc-mongo-db:27017/parse
        readinessProbe:
          tcpSocket:
            port: svr-port        
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 1
        livenessProbe:
          tcpSocket:
            port: svr-port
          initialDelaySeconds: 15
          timeoutSeconds: 1
  
      initContainers:
        - name: wait-mongo
          image: 192.168.250.75:5000/busybox
          command: ['sh', '-c', 'until nslookup svc-mongo-db; do echo waiting for svc-mongo-db; sleep 2; done;']          


---
apiVersion: v1
kind: Service
metadata:
  name: svc-parse-server
  labels:
    app: svc-parse-server
  namespace: devops-parse
spec:
  type: NodePort
  ports:
  - port: 1337
    nodePort: 31337
  selector:
    app: parse-server